export './auth_screen.dart';
export './favorite_movie_screen.dart';
export './home_screen.dart';
export './loader_screen.dart';
export './main_screen.dart';
export './movie_detailed_screen.dart';
export './profile_screen.dart';
export './search_screen.dart';
export './upcoming_movie_screen.dart';
